apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplego-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: simplego
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels: #created pods will have this label
        app: simplego
        version: v.1.0
    spec:
      containers:
      - name: simplego
        image: simplego:v.1.0
        ports:
        - containerPort: 9090
