apiVersion: v1
kind: Pod
metadata:
  name: simplego
  labels:
    app: simplego
    version: v.1.1
spec:
  containers:
  - name: simplego
    image: simplego:v.1.1
    ports:
    - containerPort: 9090