kind: Service
apiVersion: v1
metadata:
  name: simplego-svc
  # labels:
  #   app: simplego
spec:
  type: LoadBalancer
  selector:
    app: simplego
    #version: v.1.1 #map to pods with label v.1.1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
    nodePort: 30003