apiVersion: v1
kind: Service
metadata:
  name: simplego-svc
  labels:
    app: simplego
spec:
  type: NodePort
  ports:
  - port: 9090
    nodePort: 30002
    protocol: TCP
  selector:
    app: simplego
